"""The actual MIME ↔ extension table.

Each entry is ``(canonical_mime, primary_extension, *aliases)``. The
primary extension is the first one in the tuple — used by
``extension_for``. ``mime_for_extension`` checks every entry.

Coverage target: 200+ entries spanning the formats one usually sees
in HTTP responses, file managers, and developer tooling.
"""

from __future__ import annotations

from typing import Sequence

DatabaseEntry = tuple[str, ...]

# The table is intentionally readable rather than dense — a junior dev
# should be able to scan, search, and add entries without confusion.
DATABASE: Sequence[DatabaseEntry] = (
    # --- text -----------------------------------------------------------
    ("text/plain", "txt", "text", "log"),
    ("text/html", "html", "htm", "shtml"),
    ("text/css", "css"),
    ("text/csv", "csv"),
    ("text/tab-separated-values", "tsv"),
    ("text/markdown", "md", "markdown", "mdown", "mkd"),
    ("text/richtext", "rtx"),
    ("text/calendar", "ics", "ifb"),
    ("text/vcard", "vcf", "vcard"),
    ("text/x-rst", "rst"),
    ("text/x-org", "org"),
    ("text/x-yaml", "yaml", "yml"),
    ("text/x-toml", "toml"),
    ("text/x-ini", "ini", "cfg", "conf"),
    ("text/x-shellscript", "sh", "bash", "zsh"),
    ("text/x-python", "py", "pyw"),
    ("text/x-c", "c", "h"),
    ("text/x-c++", "cc", "cpp", "cxx", "hh", "hpp", "hxx"),
    ("text/x-java", "java"),
    ("text/x-go", "go"),
    ("text/x-rust", "rs"),
    ("text/x-ruby", "rb"),
    ("text/x-perl", "pl", "pm"),
    ("text/x-php", "php"),
    ("text/x-sql", "sql"),
    ("text/x-diff", "diff", "patch"),
    ("text/x-makefile", "mk", "makefile"),
    ("text/x-csrc", "c"),
    # --- application: data formats --------------------------------------
    ("application/json", "json"),
    ("application/ld+json", "jsonld"),
    ("application/manifest+json", "webmanifest"),
    ("application/json-patch+json", "json-patch"),
    ("application/xml", "xml"),
    ("application/xhtml+xml", "xhtml", "xht"),
    ("application/atom+xml", "atom"),
    ("application/rss+xml", "rss"),
    ("application/rdf+xml", "rdf"),
    ("application/yaml", "yaml", "yml"),
    ("application/toml", "toml"),
    ("application/wasm", "wasm"),
    ("application/x-www-form-urlencoded", "urlencoded"),
    ("application/javascript", "js", "mjs"),
    ("application/typescript", "ts"),
    ("application/ecmascript", "es"),
    ("application/dart", "dart"),
    ("application/sql", "sql"),
    # --- application: archives / compression ----------------------------
    ("application/zip", "zip"),
    ("application/gzip", "gz", "gzip"),
    ("application/x-bzip2", "bz2"),
    ("application/x-bzip", "bz"),
    ("application/x-xz", "xz"),
    ("application/x-7z-compressed", "7z"),
    ("application/x-tar", "tar"),
    ("application/x-rar-compressed", "rar"),
    ("application/x-lzma", "lzma"),
    ("application/x-lzip", "lz"),
    ("application/x-zstd", "zst", "zstd"),
    ("application/vnd.ms-cab-compressed", "cab"),
    ("application/x-iso9660-image", "iso"),
    ("application/x-debian-package", "deb"),
    ("application/x-redhat-package-manager", "rpm"),
    ("application/x-apple-diskimage", "dmg"),
    # --- application: documents -----------------------------------------
    ("application/pdf", "pdf"),
    ("application/postscript", "ps", "eps", "ai"),
    ("application/rtf", "rtf"),
    ("application/msword", "doc", "dot"),
    (
        "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "docx",
    ),
    ("application/vnd.ms-excel", "xls", "xlt", "xla"),
    (
        "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        "xlsx",
    ),
    ("application/vnd.ms-powerpoint", "ppt", "pps", "pot"),
    (
        "application/vnd.openxmlformats-officedocument.presentationml.presentation",
        "pptx",
    ),
    ("application/vnd.oasis.opendocument.text", "odt"),
    ("application/vnd.oasis.opendocument.spreadsheet", "ods"),
    ("application/vnd.oasis.opendocument.presentation", "odp"),
    ("application/vnd.oasis.opendocument.graphics", "odg"),
    ("application/vnd.apple.pages", "pages"),
    ("application/vnd.apple.numbers", "numbers"),
    ("application/vnd.apple.keynote", "key", "knt"),
    ("application/epub+zip", "epub"),
    ("application/x-mobipocket-ebook", "mobi"),
    ("application/vnd.amazon.ebook", "azw"),
    # --- application: misc -----------------------------------------------
    ("application/octet-stream", "bin"),
    ("application/x-bittorrent", "torrent"),
    ("application/x-shockwave-flash", "swf"),
    ("application/x-msdownload", "exe", "dll"),
    ("application/x-msi", "msi"),
    ("application/vnd.android.package-archive", "apk"),
    ("application/x-pkcs12", "p12", "pfx"),
    ("application/x-x509-ca-cert", "crt", "cer"),
    ("application/pkcs7-signature", "p7s"),
    ("application/x-sqlite3", "sqlite", "sqlite3", "db"),
    ("application/x-yaml", "yaml", "yml"),
    # --- image -----------------------------------------------------------
    ("image/png", "png"),
    ("image/jpeg", "jpg", "jpeg", "jpe"),
    ("image/gif", "gif"),
    ("image/webp", "webp"),
    ("image/avif", "avif"),
    ("image/heic", "heic"),
    ("image/heif", "heif"),
    ("image/tiff", "tiff", "tif"),
    ("image/bmp", "bmp"),
    ("image/x-icon", "ico"),
    ("image/svg+xml", "svg", "svgz"),
    ("image/x-portable-pixmap", "ppm"),
    ("image/x-portable-graymap", "pgm"),
    ("image/x-portable-bitmap", "pbm"),
    ("image/vnd.adobe.photoshop", "psd"),
    ("image/x-canon-cr2", "cr2"),
    ("image/x-canon-cr3", "cr3"),
    ("image/x-nikon-nef", "nef"),
    ("image/x-fuji-raf", "raf"),
    ("image/x-sony-arw", "arw"),
    ("image/x-adobe-dng", "dng"),
    ("image/jxl", "jxl"),
    # --- audio -----------------------------------------------------------
    ("audio/mpeg", "mp3"),
    ("audio/mp4", "m4a", "mp4a"),
    ("audio/aac", "aac"),
    ("audio/ogg", "ogg", "oga", "spx"),
    ("audio/wav", "wav"),
    ("audio/x-aiff", "aiff", "aif"),
    ("audio/flac", "flac"),
    ("audio/x-ms-wma", "wma"),
    ("audio/webm", "weba"),
    ("audio/opus", "opus"),
    ("audio/midi", "mid", "midi"),
    ("audio/x-matroska", "mka"),
    # --- video -----------------------------------------------------------
    ("video/mp4", "mp4", "m4v"),
    ("video/x-matroska", "mkv"),
    ("video/webm", "webm"),
    ("video/quicktime", "mov", "qt"),
    ("video/x-msvideo", "avi"),
    ("video/x-ms-wmv", "wmv"),
    ("video/x-flv", "flv"),
    ("video/mpeg", "mpeg", "mpg", "mpe"),
    ("video/3gpp", "3gp"),
    ("video/3gpp2", "3g2"),
    ("video/ogg", "ogv"),
    ("video/x-m4v", "m4v"),
    ("video/x-f4v", "f4v"),
    ("video/x-ms-asf", "asf"),
    ("video/MP2T", "ts", "m2ts"),
    # --- font ------------------------------------------------------------
    ("font/woff", "woff"),
    ("font/woff2", "woff2"),
    ("font/ttf", "ttf"),
    ("font/otf", "otf"),
    ("font/collection", "ttc"),
    ("font/sfnt", "sfnt"),
    ("application/vnd.ms-fontobject", "eot"),
    # --- model -----------------------------------------------------------
    ("model/gltf+json", "gltf"),
    ("model/gltf-binary", "glb"),
    ("model/obj", "obj"),
    ("model/stl", "stl"),
    ("model/vrml", "wrl"),
    # --- multipart -------------------------------------------------------
    ("multipart/form-data", "multipart"),
    ("multipart/byteranges", "byteranges"),
    ("multipart/mixed", "mixed"),
    ("multipart/alternative", "alt"),
    ("multipart/related", "related"),
    # --- message ---------------------------------------------------------
    ("message/rfc822", "eml", "mime"),
    ("message/http", "http"),
    # --- chemical / scientific ------------------------------------------
    ("chemical/x-pdb", "pdb"),
    ("chemical/x-mol", "mol"),
    ("application/x-hdf", "hdf", "h5"),
    ("application/x-netcdf", "nc"),
    ("application/x-parquet", "parquet"),
    ("application/x-feather", "feather", "arrow"),
    # --- programming language source files ------------------------------
    ("text/x-kotlin", "kt", "kts"),
    ("text/x-swift", "swift"),
    ("text/x-scala", "scala"),
    ("text/x-haskell", "hs"),
    ("text/x-elixir", "ex", "exs"),
    ("text/x-erlang", "erl"),
    ("text/x-lua", "lua"),
    ("text/x-r", "r"),
    ("text/x-julia", "jl"),
    ("text/x-fsharp", "fs", "fsx"),
    ("text/x-vbscript", "vbs"),
    ("text/x-csharp", "cs"),
    ("text/x-latex", "tex", "ltx"),
    ("text/x-bibtex", "bib"),
    ("text/x-clojure", "clj", "cljs"),
    ("text/x-vue", "vue"),
    ("text/x-svelte", "svelte"),
    ("text/x-jsx", "jsx"),
    ("text/x-tsx", "tsx"),
    ("text/x-graphql", "graphql", "gql"),
    ("text/x-dockerfile", "dockerfile"),
    ("text/x-gitignore", "gitignore"),
)
